### PR TITLE
Building API/server

### PR DESCRIPTION
**Pull request by vbaobao**
**Purpose:**
- Build an API that the React component will use to fetch data based on an item's ID and/or name.
- Should not exceed 100 lines of code.
- Sets up API call to the endpoint '/api/sizes/:id' via localhost.

**Things to review:**
- server.js
- App.jsx is currently just a placeholder. Maybe review the boilerplate, but content is not final.

**Other changes:**
- Changes in seed.js, database.js, seed.test.js are edits made due to suggested changes from a previous branch.
- styles.css is an empty file

[Trello ticket: gWD4Mhgh](https://trello.com/c/gWD4Mhgh)

### CODE REVIEW

**Comment by joshparkerj** [comment]
I notice that when you run the seed script, it says connection successful but doesn't exit when it's done. It's probably fine, but it seems unexpected. I'd expect it to close the connection and exit when it's finished seeding.

**Comment by joshparkerj** [comment]
Something doesn't seem to be working. I'm guessing that maybe the getProductSize function in database.js is supposed to take a callback function?

**Comment by joshparkerj** [comment]
Last thing I'd change is in the App.jsx, it's setting the contents of the array to state itself when it's probably meant to be set to data. So, I'd change it from this.setState(res.data); to this.setState({data: res.data});

**Comment by vbaobao** [comment]
Thanks, I removed the callbacks due to a previous feedback. I'll put them back in. Also, thank you for noting about the MongoDB connection made during seeding. I wasn't aware that needed to be closed, I thought it would be fine to leave it open. But probably better to close it. Also, thanks for catching the setState() error. I wasn't testing frontend changes, so I missed it.

**Pull request merged**
